#!/usr/bin/env python

#Import open AI OS and System Modules

import openai
import os
import sys

openai.api_key = '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'

messages = [
        {"role": "system", "content": "You are a helpful assistant."},
]

while True:
    message = input("You: ")
    message = "Give only the bash command to " + message + "without any other descriptive text"
    if message:
        messages.append(
                {"role": "user", "content": message},
        )
        chat_completion = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=messages
        )
    answer = chat_completion.choices[0].message.content
    nw = answer.split("````")[0]
    print(f"{nw}")
    messages.append({"role": "assistant", "content": nw})